const CREATE_ROOM = 'CREATE_ROOM';
const JOIN_ROOM = 'JOIN_ROOM';
const DELETE_ROOM = 'DELETE_ROOM';
const LEVEL_SCORE = 'LEVEL_SCORE';
const UPDATE_LEADERBOARD = 'UPDATE_LEADERBOARD';

module.exports = { CREATE_ROOM, JOIN_ROOM, DELETE_ROOM, LEVEL_SCORE, UPDATE_LEADERBOARD };