const CREATE_ROOM = 'CREATE_ROOM';
const JOIN_ROOM_REQUEST = 'JOIN_ROOM_REQUEST';
const ACCEPTED_JOIN_ROOM = 'ACCEPTED_JOIN_ROOM';
const START_GAME = 'START_GAME';
const UPDATE_LEADERBOARD = 'UPDATE_LEADERBOARD';
const NEXT_LEVEL = 'NEXT_LEVEL';
const END_GAME = 'END_GAME';
const DELETE_ROOM = 'DELETE_ROOM';
const ERROR = 'ERROR';
const USERS = 'USERS';

module.exports = { CREATE_ROOM, JOIN_ROOM_REQUEST, ACCEPTED_JOIN_ROOM, START_GAME, UPDATE_LEADERBOARD, NEXT_LEVEL, END_GAME, DELETE_ROOM, ERROR, USERS };