exports.CREATE_ROOM = 'CREATE_ROOM';
exports.JOIN_ROOM_REQUEST = 'JOIN_ROOM_REQUEST';
exports.ACCEPTED_JOIN_ROOM = 'ACCEPTED_JOIN_ROOM';
exports.DENY_REQUEST = 'DENY_REQUEST';
exports.REMOVE_USER = 'REMOVE_USER';
exports.EXIT_ROOM = 'EXIT_ROOM';
exports.GET_ALL_DATA = 'GET_ALL_DATA';
exports.REMOVED = 'REMOVED';
exports.START_GAME = 'START_GAME';
exports.DELETE_ROOM = 'DELETE_ROOM';

exports.UPDATE_LEADERBOARD = 'UPDATE_LEADERBOARD';
exports.NEXT_LEVEL = 'NEXT_LEVEL';
exports.JOIN_GAME_ROOM = 'JOIN_GAME_ROOM';
exports.PLAYING = 'PLAYING';
exports.EXIT_GAME = 'EXIT_GAME';
exports.GAME_OVER = 'GAME_OVER';