exports.JOIN_ROOM_REQUEST = 'JOIN_ROOM_REQUEST';
exports.ACCEPTED_JOIN_ROOM = 'ACCEPTED_JOIN_ROOM';
exports.UPDATE_LEADERBOARD = 'UPDATE_LEADERBOARD';
exports.NEXT_LEVEL = 'NEXT_LEVEL';
exports.ERROR = 'ERROR';
exports.ROOM_CREATED = 'ROOM_CREATED';
exports.DENY_REQUEST = 'DENY_REQUEST';
exports.GET_ALL_DATA = 'GET_ALL_DATA';